### ISSUE TITLE
Failed to register symbol `glfwGetWaylandMonitor`

### ISSUE THREAD

**Issue by retraigo** [deno-windowing/dwm#16]
Unable to initialize `Window` or `WindowCanvas`.

The symbols `glfwGetWaylandMonitor` or `glfwGetWaylandWindow` are missing when attempting to run (the missing symbol keeps changing between the two each time I run with `--reload`).

edit: `glfwGetWaylandDisplay` too.

```st
[caligo@fedora test]$ deno run -A --unstable --reload chart.ts 
error: Uncaught Error: Failed to register symbol glfwGetWaylandMonitor: Could not obtain symbol from the library: /home/caligo/.cache/deno/glfw3_v3-4-0.so: undefined symbol: glfwGetWaylandMonitor
  mod = Deno.dlopen(tmp, symbols);
             ^
    at new DynamicLibrary (internal:ext/ffi/00_ffi.js:368:48)
    at Object.dlopen (internal:ext/ffi/00_ffi.js:500:12)
    at https://deno.land/x/dwm@0.3.0/src/platform/glfw/ffi.ts:463:14
```

System Info:
```yml
OS: Fedora Linux 37 (KDE Plasma) x86_64 
Kernel: 6.1.11-200.fc37.x86_64 
WM: kwin (wayland)
CPU: Intel i5-10400F (12) @ 4.300GHz 
GPU: NVIDIA GeForce RTX 3060 Ti
Memory: 7791MiB / 15887MiB 
```
